version: '3.9'

services:
  backend-app:
    build: .
    image: bike-rental
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bike-rental

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "bike-rental"
    ports:
      - 5432:5432