version: '3.9'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "bike-rental"
    ports:
      - 5432:5432